const IconName = {
  plusCircle: 'ant-design:plus-circle-filled',
  arrowLeft: 'bi:arrow-left',
  arrowRight: 'bi:arrow-right',
  arrowUp: 'bx:up-arrow-circle',
  pluseSquare: 'akar-icons:plus',
  scroll: 'gg:scroll-v',
  close: 'ant-design:close-circle-outlined',
  search: 'akar-icons:search',
  chevronDown: 'akar-icons:chevron-down',
  chevronRight: 'akar-icons:chevron-right',
  draft: 'carbon:rule-draft',
  manager: 'arcticons:qmanager',
  acounting: 'codicon:account',
  delete: 'ant-design:delete-outlined',
  edit: 'bx:edit-alt',
  doc: 'gg:loadbar-doc',
  checked: 'akar-icons:circle-check-fill',
  clock: 'ant-design:clock-circle-filled',
  bell: 'bi:bell-fill',
  moreHorizontal: 'akar-icons:more-horizontal',
  moreVertical: 'akar-icons:more-vertical',
  width: 'ant-design:column-width-outlined',
  height: 'ant-design:column-height-outlined',
  address: 'majesticons:map-marker-area-line',
  landUseType: 'mdi:land-plots',
  agriculture: 'carbon:agriculture-analytics',
  residential: 'maki:residential-community',
  totalArea: 'icon-park-outline:sum',
  location: 'arcticons:manga-plus',
  worldHighway: 'mdi:highway',
  landDirection: 'bi:compass',
  legal: 'carbon:document',
  remark: 'arcticons:note-it',
  dollar: 'dashicons:money-alt',
  landLotNo: 'cil:map',
  mapNo: 'clarity:map-outline-badged',
  seeMore: 'eva:log-in-fill',
  description: 'ic:sharp-folder-special',
  document: 'carbon:document',
  pdf: 'ant-design:file-pdf-outlined',
  image: 'ant-design:file-image-outlined',
  excel: 'ant-design:file-excel-outlined',
  word: 'ant-design:file-word-outlined',
  outlook: 'vscode-icons:file-type-outlook',
  vietnam: 'twemoji:flag-vietnam',
  england: 'twemoji:flag-united-kingdom',

};

export default IconName;
